import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/Redux-Toolkit/providers/ReduxProvider";


export const metadata: Metadata = {
  title: "Himalyan Roots",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
