import type { Metadata } from "next";
import Header from "../../common/Header";
import Footer from "../../common/footer";
// import Header from "../../common/header";
// import Footer from "../../common/footer";


export const metadata: Metadata = {
    title: "Main Pages",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
        {/* <Header /> */}
        <Header/>
            <main className="">
                {/* mt-27 */}
                {children}
            </main>
            <Footer />
            {/* <Footer/>  */}
        </>

    );
}

